### PR TITLE
DnsServerSetting: Refactor the resource to use cmdlet *-DnsServerSetting

### LINKED ISSUE #101: DnsServerSetting: PowerShell Cmdlet failed: Convert property `'AllowUpdate'` value from type `'BOOLEAN'` to type `'UINT32'` failed
#### Details of the scenario you tried and the problem that is occurring

Trying to set DNS setting "AllowUpdate" to true.

```
dsc_resource 'authoritative_settings' do
		module_name 'xDnsServer'
		resource :xDnsServerSetting
		property :Name, 'authoritative_settings'
		property :NoRecursion, true
		property :LogLevel, 24865
		property :AllowUpdate, true
		property :LogFilePath, 'C:\\dns\\dns.log'
		#property :ListenAddresses, dnsip
		ignore_failure true
	end
```
or

```
dsc_resource 'authoritative_settings' do
		module_name 'xDnsServer'
		resource :xDnsServerSetting
		property :Name, 'authoritative_settings'
		property :NoRecursion, true
		property :LogLevel, 24865
		property :AllowUpdate, '1'
		property :LogFilePath, 'C:\\dns\\dns.log'
		#property :ListenAddresses, dnsip
		ignore_failure true
	end
```

#### Verbose logs showing the problem
    ================================================================================
    Error executing action `run` on resource 'dsc_resource[authoritative_settings]'
    ================================================================================

    Chef::Exceptions::PowershellCmdletException
    -------------------------------------------
    PowerShell Cmdlet failed: Convert property 'AllowUpdate' value from type 'BOOLEAN' to type 'UINT32' failed
     At line:12, char:2
     Buffer:
    horitative_settings";
    };^
    insta
        + CategoryInfo          : SyntaxError: (root/Microsoft/...gurationManager:String) [], CimException
        + FullyQualifiedErrorId : MiClientApiError_Failed
        + PSComputerName        : localhost

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/fisher-dns-windows/recipes/default.rb

     70:        dsc_resource 'authoritative_settings' do
     71:                module_name 'xDnsServer'
     72:                resource :xDnsServerSetting
     73:                property :Name, 'authoritative_settings'
     74:                property :NoRecursion, true
     75:                property :LogLevel, 24865
     76:                property :AllowUpdate, true
     77:                property :LogFilePath, 'C:\\dns\\dns.log'
     78:                #property :ListenAddresses, dnsip
     79:                ignore_failure true
     80:        end
     81:        registry_key "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\DNS\\Parameters" do

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/fisher-dns-windows/recipes/default.rb:70:in `from_file'

    dsc_resource("authoritative_settings") do
      action [:run]
      default_guard_interpreter :default
      properties {Name=>"authoritative_settings", NoRecursion=>true, LogLevel=>24865, AllowUpdate=>true, LogFilePath=>"C:\\dns\\dns.log"}
      resource :xDnsServerSetting
      declared_type :dsc_resource
      cookbook_name "fisher-dns-windows"
      recipe_name "default"
      module_name "xDnsServer"
      ignore_failure true
    end

    System Info:
    ------------
    chef_version=14.10.9
    platform=windows
    platform_version=6.3.9600
    ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```
dsc_resource 'authoritative_settings' do
		module_name 'xDnsServer'
		resource :xDnsServerSetting
		property :Name, 'authoritative_settings'
		property :NoRecursion, true
		property :LogLevel, 24865
		property :AllowUpdate, true
		property :LogFilePath, 'C:\\dns\\dns.log'
		#property :ListenAddresses, dnsip
		ignore_failure true
	end
```
or

```
dsc_resource 'authoritative_settings' do
		module_name 'xDnsServer'
		resource :xDnsServerSetting
		property :Name, 'authoritative_settings'
		property :NoRecursion, true
		property :LogLevel, 24865
		property :AllowUpdate, '1'
		property :LogFilePath, 'C:\\dns\\dns.log'
		#property :ListenAddresses, dnsip
		ignore_failure true
	end
```

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19376.amd64fre.winblue_ltsb_escrow.190520-1700
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)

1.13.0.0

### LINKED ISSUE #185: BREAKING CHANGE: DnsServerSetting: Switch to use `Get-DnsServerSetting` and `Set-DnsServerSetting`
#### Details of the scenario you tried and the problem that is occurring
Currently this resource can change forwarders, so can the resource _xDnsServerForwarder_. This can result in a ping-pong behavior when both resources are used in the same configuration and sets two different desired states,

#### Verbose logs showing the problem
Not available.

#### Suggested solution to the issue
Instead of using CIM to change the settings, the _xDnsServerSetting_ resource should use `Get-DnsServerSetting` and `Set-DnsServerSetting`. Using those cmdlet it will remove the property Forwarders from the resource _xDnsServerSetting_ and make sure that only _xDnsServerForwarder_ can be used for this task.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Configuration xDnsServerSetting_CurrentNode_Config
{
    Import-DscResource -ModuleName 'xDnsServer'

    Node localhost
    {
        xDnsServerSetting 'DnsServerProperties'
        {
            DnsServer           = 'localhost'
            Forwarders         = @('168.63.129.16', '168.63.129.18')
        }

        xDnsServerForwarder 'SetForwarders'
        {
            IsSingleInstance = 'Yes'
            IPAddresses      = @('168.63.129.16', '192.168.0.11')
            UseRootHint      = $false
        }
    }
}
```

#### The operating system the target node is running
All Windows.

#### Version and build of PowerShell the target node is running
Windows PowerShell 5.1

#### Version of the DSC module that was used
Code in main

### LINKED ISSUE #252: BREAKING CHANGE: xDnsServerSetting: Remove properties `DsPollingInterval` and `DsTombstoneInterval`
#### Details of the scenario you tried and the problem that is occurring
Suggest removing the properties `DsPollingInterval` and `DsTombstoneInterval` from the resource **xDnsServerSetting** to avoid ping-pong behavior. Instead those should be enforced by the resource **DnsServerDsSetting**.

#### Verbose logs showing the problem
n/a

#### Suggested solution to the issue
See above. Related to issue #251.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
n/a

#### The operating system the target node is running
Any Windows

#### Version and build of PowerShell the target node is running
Windows PowerShell

#### Version of the DSC module that was used
3.0.0 preview

### PR DESCRIPTION
**Pull request by johlju**
### Pull Request (PR) description
- DnsServerSetting
  - BREAKING CHANGE: A few properties that are not supported by any DNS
    Server PowerShell cmdlet was moved to the new resource _DnsServerSettingLegacy_.
  - Changed to use `Get-DnsServerSetting` and `Set-DnsServerSetting`
    ([issue #185](https://github.com/dsccommunity/xDnsServer/issues/185)).
  - BREAKING CHANGE: The property `DisableAutoReverseZones` have been renamed
    to `DisableAutoReverseZone`.
  - BREAKING CHANGE: The property `ListenAddresses` have been renamed
    to `ListeningIPAddress`.
  - BREAKING CHANGE: The property `AllowUpdate` was changed to a boolean
    value (`$true` or `$false`) since that is what the cmdlet `Set-DnsServerSetting`
    is expecting (related to [issue #101](https://github.com/dsccommunity/xDnsServer/issues/101)).
  - BREAKING CHANGE: The property `EnableDnsSec` was changed to a boolean
    value (`$true` or `$false`) since that is what the cmdlet `Set-DnsServerSetting`
    is expecting.
  - BREAKING CHANGE: The property `ForwardDelegations` was changed to a boolean
    value (`$true` or `$false`) since that is what the cmdlet `Set-DnsServerSetting`
    is expecting.
  - BREAKING CHANGE: The properties `DsPollingInterval` and `DsTombstoneInterval`
    has been removed ([issue #252](https://github.com/dsccommunity/DnsServerDsc/issues/252)).
    Use the resource _DnsServerDsSetting_ to enforce these properties.
- DnsServerSettingLegacy
  - A new resource to manage legacy DNS Server settings that are not supported
    by any DNS Server PowerShell cmdlet.

### This Pull Request (PR) fixes the following issues
- Fixes #185
- Fixes #101 
- Fixes #252

### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/257)

### CODE REVIEW

**Comment by johlju** [comment]
Sending in draft to get comments while I continue working on this. Left to do:

- Need to add the additional properties to DnsServerSetting
- Need to add unit tests for both resources
- Need to add integration tests for both resources
- Need to add/update examples for both resources

**Review by Sudman1 — COMMENTED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/257)* status: 1 of 18 files reviewed, 1 unresolved discussion (waiting on @johlju)

*[a discussion](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/257#-Ma1CV2KCJwm_I0ouYOl:-Ma1CV2KCJwm_I0ouYOm:bxf7go2) (no related file):*
Could we reimplement this resource using a class? It seems like ResourceBase could do the heavy lifting here quite easily. The most difficult part would be the test cases and examples, but you seem to already have those sorted.

---

**Comment by johlju** [comment]
*[a discussion](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/257#-Ma1CV2KCJwm_I0ouYOl:-Ma1fJUp3LItEW0MehHE:b51gln9) (no related file):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

Could we reimplement this resource using a class? It seems like ResourceBase could do the heavy lifting here quite easily. The most difficult part would be the test cases and examples, but you seem to already have those sorted.
</blockquote></details>

We could have (and I thought about it), but I opted to just change the existing logic and not do a whole new resources. It was easier to get this out of the door. My thought was that another PR can refactor it again to a class without being a breaking change. 

---

**Comment by johlju** [comment]
I need to work on the integration tests which gonna take the longest. 

I probably have to run an integration tests that sets a "bad but passing" state, and then set all properties back to a "known-working" so I don't break any other tests because a setting was flipped. 
I might just take all properties from current state, then run integration tests to set a "bad but passing" state, then set it back to the properties from the first current state. 

Some properties might not be able to be tested because we run the DNS standalone - we'll see. If there are any properties then we have to document those that they are not tested.

**Comment by Sudman1** [comment]
> I need to work on the integration tests which gonna take the longest.
> 
> I probably have to run an integration tests that sets a "bad but passing" state, and then set all properties back to a "known-working" so I don't break any other tests because a setting was flipped.
> I might just take all properties from current state, then run integration tests to set a "bad but passing" state, then set it back to the properties from the first current state.
> 
> Some properties might not be able to be tested because we run the DNS standalone - we'll see. If there are any properties then we have to document those that they are not tested.

I suppose we could install and configure AD features - unless a reboot is required - I don't remember of the top of my head if it is 🤔

**Comment by johlju** [comment]
It’s not possible to run AD features in the build worker (it needs restart). But we should add a framework to run integrations tests locally. I started working on that in ActiveDirectoryDsc long time ago but haven’t gotten back to it. @gaelcolas also started working on a framework using Test Kitchen but that is also paused I think. 😊

**Comment by johlju** [comment]
Now all the previous properties in the integration tests changes the values. Now  I just need to get the other 20 or so properties in.

**Comment by johlju** [comment]
This one is ready for review now. I had two issues with this that I opted to ignore to get this resource out of the door. Since the properties have not been available the community can look at those at a later date, in another PR. 🙂 The issues in question is issue #259 and issue #260.

**Review by Sudman1 — COMMENTED** [review]
> Reviewed 2 of 13 files at r1, 1 of 7 files at r2, 6 of 13 files at r3, 6 of 8 files at r4, 4 of 5 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/257)* status: all files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1, line 157 at r8](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/257#-MaPTFYP8UtIwkKJ8Tt1:-MaPTFYP8UtIwkKJ8Tt2:b-257x95) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/f75ae94842dc9f29142253e54ff9438f0ccb9725/source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1#L157)):*
> ```PowerShell
> 
>     .PARAMETER AddressAnswerLimit
>         See schema MOF.
> ```

I've never seen this done before. Is this legitimate production code for MOF-based resources, or is this just a placeholder?
___
*[source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1, line 618 at r8](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/257#-MaPTdJRBkjP8wJmrvAk:-MaPTdJRBkjP8wJmrvAl:ba0ps9p) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/f75ae94842dc9f29142253e54ff9438f0ccb9725/source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1#L618)):*
> ```PowerShell
>         [Parameter()]
>         [System.String]
>         $ZoneWritebackInterval
> ```

This is a lot of settings for one resource. In the future should we consider refactoring these into separate resources based on some logical grouping? maybe when we move this to a class-based resource?

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/257)* status: all files reviewed, 2 unresolved discussions (waiting on @Sudman1)

___
*[source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1, line 157 at r8](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/257#-MaPTFYP8UtIwkKJ8Tt1:-MaPWejx-KedcrvnrsVB:bc048l1) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/f75ae94842dc9f29142253e54ff9438f0ccb9725/source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1#L157)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

I've never seen this done before. Is this legitimate production code for MOF-based resources, or is this just a placeholder?
</blockquote></details>

It was a placeholder, I will fix it during the week. I was on a laptop this weekend so didn’t want to copy paste between the files when I didn’t have a big monitor. 😊
___
*[source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1, line 618 at r8](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/257#-MaPTdJRBkjP8wJmrvAk:-MaPX8Eo9WhRSMOgio-7:b-qbrkyx) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/f75ae94842dc9f29142253e54ff9438f0ccb9725/source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1#L618)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

This is a lot of settings for one resource. In the future should we consider refactoring these into separate resources based on some logical grouping? maybe when we move this to a class-based resource?
</blockquote></details>

I think MS made one cmdlet featuring all these since there is class that covers these. But we can absolutely group them into several resources if there is some logical grouping. Rather do that when we have a class though.

**Review by Sudman1 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/257#-:-MaP_6KkBPqXsxOir14W:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1, line 157 at r8](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/257#-MaPTFYP8UtIwkKJ8Tt1:-MaP_CIkB8CaedT3sLus:b58e9cy) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/f75ae94842dc9f29142253e54ff9438f0ccb9725/source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1#L157)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

It was a placeholder, I will fix it during the week. I was on a laptop this weekend so didn’t want to copy paste between the files when I didn’t have a big monitor. 😊
</blockquote></details>

In that case, I'll leave this comment open until that's resolved.
___
*[source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1, line 618 at r8](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/257#-MaPTdJRBkjP8wJmrvAk:-MaP_UQ_EidAzVbcvsge:brfbgj8) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/f75ae94842dc9f29142253e54ff9438f0ccb9725/source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1#L618)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I think MS made one cmdlet featuring all these since there is class that covers these. But we can absolutely group them into several resources if there is some logical grouping. Rather do that when we have a class though. 
</blockquote></details>

Fair enough. I think it would make it more manageable to find a way to break it up. I'll open an issue to be addressed in a future release.

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/257)* status: 18 of 20 files reviewed, 2 unresolved discussions (waiting on @Sudman1)

___
*[source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1, line 157 at r8](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/257#-MaPTFYP8UtIwkKJ8Tt1:-MacvbnD9DZIP-z_Hji7:b-896fix) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/f75ae94842dc9f29142253e54ff9438f0ccb9725/source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1#L157)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

In that case, I'll leave this comment open until that's resolved.
</blockquote></details>

Done.
___
*[source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1, line 618 at r8](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/257#-MaPTdJRBkjP8wJmrvAk:-Macvcbe4c37f3IKYASh:b-e44wxo) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/f75ae94842dc9f29142253e54ff9438f0ccb9725/source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1#L618)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

Fair enough. I think it would make it more manageable to find a way to break it up. I'll open an issue to be addressed in a future release. 
</blockquote></details>

Done. Sounds good, thanks!

**Comment by johlju** [comment]
I merge this when the test passes.

**Pull request merged**
