### PR TITLE
DnsServerCache: Add new resource to enforce cache settings

### LINKED ISSUE #196: DnsServerCache: New resource proposal
### Description
Suggest adding a new resource that changes DNS server cache settings. Using the commands [`Get-DnsServerCache`](https://docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsservercache) and [`Set-DnsServerCache`](https://docs.microsoft.com/en-us/powershell/module/dnsserver/set-dnsservercache).

### Proposed properties
 - **`DnsServer` <Key, String>** - The host name of the DNS server to change, or use `'localhost'` for the current node.
 - **`IgnorePolicies` <Write, Boolean>** - Indicates whether to ignore policies for this cache.
 - **`LockingPercent` <Write, UInt32>** - Specifies a percentage of the original Time to Live (TTL) value that caching can consume. Cache locking is configured as a percent value. For example, if the cache locking value is set to 50, the DNS server does not overwrite a cached entry for half of the duration of the TTL. By default, the cache locking percent value is 100. This value means that the DNS server will not overwrite cached entries for the entire duration of the TTL.
 - **`MaxKBSize` <Write, UInt32>** - Specifies the maximum size, in kilobytes, of the memory cache of a DNS server.
 - **`MaxNegativeTtl` <Write, String>** - Specifies whether to enable the server to probe other servers to determine whether they support EDNS.
 - **`MaxTtl` <Write, String>** - Specifies how long (0 to 2592000 seconds) a record is saved in cache. The value must be provided as a TimeSpan. If the TimeSpan is set to 0 seconds, the DNS server does not cache records. The default setting is one day (86,400 seconds).
 - **`PollutionProtection` <Write, Boolean>** - Specifies whether DNS filters name service (NS) resource records that are cached. Valid values are zero, which caches all responses to name queries and is the default value; and one, which caches only the records that belong to the same DNS subtree. When you set this parameter value to False, cache pollution protection is disabled. A DNS server caches the Host (A) record and all queried NS resources that are in the DNS server zone. In this case, DNS can also cache the NS record of an unauthorized DNS server. This event causes name resolution to fail or to be appropriated for subsequent queries in the specified domain. When you set the value for this parameter to True, the DNS server enables cache pollution protection and ignores the Host (A) record. The DNS server performs a cache update query to resolve the address of the NS if the NS is outside the zone of the DNS server. The additional query minimally affects DNS server performance. For more information about DNS cache locking, see [DNS Cache Locking](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/ee683892(v=ws.10)). For more information about cache pollution protection, see [Securing the DNS Server Service](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc731367(v=ws.11)). For more information about NS resource records, see [Managing resource records](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc783389(v=ws.10)).
- **`StoreEmptyAuthenticationResponse` <Write, Boolean>** - Specifies whether a DNS server stores empty authoritative responses in the cache (RFC-2308).

### Special considerations or limitations
The parameters `MaxNegativeTtl` and `MaxTtl` are of the type `[String]` that should be converted to `[TimeSpan]` similar to the `TTL` parameter here:
https://github.com/dsccommunity/xDnsServer/blob/dbcdb067ce905e7c3fc5f74d1ad787c3166f33ba/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L200-L203

The parameters `EnablePollutionProtection`, `MaxTtl` and `MaxNegativeTtl` replaces the properties `SecureResponses`, `MaxCacheTTL` and `MaxNegativeCacheTTL` in the resource **xDnsServerSetting**, To avoid ping-pong behavior those properties should be removed from the resource **xDnsServerSetting** once this issue is resolved.

### PR DESCRIPTION
**Pull request by johlju**
#### Added

- xDnsServer
  - Added new resource
    - _DnsServerCache_ - resource to enforce cache settings (issue #196).
  - Added new private function `Get-ClassName` that returns the class name
    or optionally an array with the class name and all inherited base class
    named.
  - Added new private function `Get-LocalizedDataRecursive` that gathers
    all localization strings from an array of class names. This can be used
    in classes to be able to inherit localization strings from one or more
    base class. If a localization string key exist in a parent class's
    localization string file it will override the localization string key
    in any base class.

#### Changed

- ResourceBase
  - Added support for inherit localization strings and also able to override
    a localization string that exist in a base class.

### This Pull Request (PR) fixes the following issues

- Fixes #196

### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xdnsserver/230)

### CODE REVIEW

**Comment by johlju** [comment]
@sudman1 if you have a few minutes over, would be great if you had the time to review this. I need to merge it tomorrow morning anyway, before I rename the repo (afraid it will be terrible to rebase the PR otherwise).

**Review by Sudman1 — COMMENTED** [review]
The builds don't seem to be completing, so I can't speak directly to code coverage as I would like. But my comments here are mostly discussion or suggestion. As long as it can pass the build pipeline, there don't seem to be any show-stoppers here.

> Reviewed 13 of 15 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/230#-:-MWlC8TCB6cBbpPbE5AL:bgbwir9)* status: all files reviewed, 3 unresolved discussions (waiting on @johlju)

___
*[source/en-US/ResourceBase.strings.psd1, line 8 at r3](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/230#-MWl92Us3s3gmZU6DKPq:-MWl92Ut7EjJVhIZdKSv:blenn4t) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/c65aedb7c2500953f311adf439fdd98f4b1538fa/source/en-US/ResourceBase.strings.psd1#L8)):*
> ```PowerShell
> 
> ConvertFrom-StringData @'
>     NoPropertiesToSet = All properties are in desired state. (RB0001)
> ```

It would be nice to see some default values added to this file, maybe not in this PR. But a generic string for NotInDesiredState, InDesiredState, and SetProperty would be helpful for future class implementations. Something along the lines of:

```
    NotInDesiredState = The {0} settings for the server '{1}' is not in desired state. (RB0002)
    InDesiredState = The {0} settings for the server '{1}' is in desired state. (RB0003)
    SetProperty = The {0} property '{1}' will be set to '{2}'. (RB0004)
```

Where the args for the string format would be `$className, $DnsServer` or `$className, $prop, $val`
___
*[source/Private/Get-ClassName.ps1, line 24 at r3](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/230#-MWl5Ntn4xyd4jmSw4Mb:-MWl5Ntn4xyd4jmSw4Mc:bgv9m14) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/c65aedb7c2500953f311adf439fdd98f4b1538fa/source/Private/Get-ClassName.ps1#L24)):*
> ```PowerShell
>         [Parameter()]
>         [System.Management.Automation.SwitchParameter]
>         $Recursive
> ```

By convention, to match with other cmdlet usage, this should probably be $Recurse instead of $Recursive
___
*[source/Private/Get-LocalizedDataRecursive.ps1, line 8 at r3](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/230#-MWl6DBUA6wDGp_GL6Nr:-MWl6DBVBg7EGjBW-UYA:ba59xsd) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/c65aedb7c2500953f311adf439fdd98f4b1538fa/source/Private/Get-LocalizedDataRecursive.ps1#L8)):*
> ```
>         If a localization string key exist in a parent class's localization string
>         file it will override the localization string key in any base class.
> ```

Technically speaking, that's not what's happening here - and I think it should be stated somewhere what is actually happening - either here or inline with the code:

This is not implemented as an override. If we reversed the array, then we could implement it that way. However, whatever order the class names are presented to the function is the precedence order of the strings. There is actually no overwriting of existing hash table entries occurring here. It is a first-come-first-serve solution. It just happens (by design) that the array generated by the Get-Class function returns class names in child -> parent order.

**Comment by johlju** [comment]
The build do complete, but it shows the previous status checks prior to renaming the repo. It throw me too at first, but scrolling down the 'DnsServerDsc.*' status checks are all green.

**Comment by johlju** [comment]
I will fix the review comments. Thank you! 😄

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/230)* status: 9 of 15 files reviewed, 3 unresolved discussions (waiting on @Sudman1)

___
*[source/en-US/ResourceBase.strings.psd1, line 8 at r3](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/230#-MWl92Us3s3gmZU6DKPq:-MWmh5EJ9KqC8M7JuGLd:b-896fix) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/c65aedb7c2500953f311adf439fdd98f4b1538fa/source/en-US/ResourceBase.strings.psd1#L8)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

It would be nice to see some default values added to this file, maybe not in this PR. But a generic string for NotInDesiredState, InDesiredState, and SetProperty would be helpful for future class implementations. Something along the lines of:

```
    NotInDesiredState = The {0} settings for the server '{1}' is not in desired state. (RB0002)
    InDesiredState = The {0} settings for the server '{1}' is in desired state. (RB0003)
    SetProperty = The {0} property '{1}' will be set to '{2}'. (RB0004)
```

Where the args for the string format would be `$className, $DnsServer` or `$className, $prop, $val`
</blockquote></details>

Done.
___
*[source/Private/Get-ClassName.ps1, line 24 at r3](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/230#-MWl5Ntn4xyd4jmSw4Mb:-MWmh9HI-AWTnJBaqkVE:bw9wcge) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/c65aedb7c2500953f311adf439fdd98f4b1538fa/source/Private/Get-ClassName.ps1#L24)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

By convention, to match with other cmdlet usage, this should probably be $Recurse instead of $Recursive
</blockquote></details>

Done. I had a tiny feeling yesterday that `Recursive` was wrong. Good catch!
___
*[source/Private/Get-LocalizedDataRecursive.ps1, line 8 at r3](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/230#-MWl6DBUA6wDGp_GL6Nr:-MWmcTWE1N8TwgF7dOPx:b-idabb7) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/c65aedb7c2500953f311adf439fdd98f4b1538fa/source/Private/Get-LocalizedDataRecursive.ps1#L8)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

> ```
>         If a localization string key exist in a parent class's localization string
>         file it will override the localization string key in any base class.
> ```

Technically speaking, that's not what's happening here - and I think it should be stated somewhere what is actually happening - either here or inline with the code:

This is not implemented as an override. If we reversed the array, then we could implement it that way. However, whatever order the class names are presented to the function is the precedence order of the strings. There is actually no overwriting of existing hash table entries occurring here. It is a first-come-first-serve solution. It just happens (by design) that the array generated by the Get-Class function returns class names in child -> parent order.
</blockquote></details>

Done. Reprashed.

I had the terminology mixed up. I know now the base class is a parent class, and the current class is the child class. I thought of the base class as the child class, that is why the mix up above. Thanks for setting me straight, I had to read up on it. :slightly_smiling_face:  Plus as you said, the order of the array determines the string keys used.

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/230)* status: 9 of 15 files reviewed, 3 unresolved discussions (waiting on @Sudman1)

___
*[source/en-US/ResourceBase.strings.psd1, line 8 at r3](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/230#-MWl92Us3s3gmZU6DKPq:-MWmhas6DFotljaP93Vg:b-896fix) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/c65aedb7c2500953f311adf439fdd98f4b1538fa/source/en-US/ResourceBase.strings.psd1#L8)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[source/Private/Get-ClassName.ps1, line 24 at r3](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/230#-MWl5Ntn4xyd4jmSw4Mb:-MWmh__D9Cdq2zy4Vq7c:b-896fix) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/c65aedb7c2500953f311adf439fdd98f4b1538fa/source/Private/Get-ClassName.ps1#L24)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. I had a tiny feeling yesterday that `Recursive` was wrong. Good catch!
</blockquote></details>

Done.
___
*[source/Private/Get-LocalizedDataRecursive.ps1, line 8 at r3](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/230#-MWl6DBUA6wDGp_GL6Nr:-MWmha25CGiYZFb-hK7v:b-896fix) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/c65aedb7c2500953f311adf439fdd98f4b1538fa/source/Private/Get-LocalizedDataRecursive.ps1#L8)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. Reprashed.

I had the terminology mixed up. I know now the base class is a parent class, and the current class is the child class. I thought of the base class as the child class, that is why the mix up above. Thanks for setting me straight, I had to read up on it. :slightly_smiling_face:  Plus as you said, the order of the array determines the string keys used.
</blockquote></details>

Done.

**Comment by johlju** [comment]
Hmm. The Done button didn't disappear from Reviewable as it normally does. That's why the duplicate post.

**Comment by johlju** [comment]
I will merge this now. If you see any issues with this PR after my last commit to fix your suggestions I will make sure to fix them after I renamed the module and resources.

**Review by Sudman1 — COMMENTED** [review]
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/230)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by Sudman1** [comment]
I didn't see any additional issues.

**Pull request merged**
