### PR TITLE
DnsServerRecursion: New resource proposal

### LINKED ISSUE #198: DnsServerRecursion: New resource proposal
### Description
Suggest adding a new resource that changes DNS server recursion settings. Using the commands [`Get-DnsServerRecursion`](https://docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserverrecursion) and [`Set-DnsServerRecursion`](https://docs.microsoft.com/en-us/powershell/module/dnsserver/set-dnsserverrecursion).

### Proposed properties
 - **`DnsServer` <Key, String>** - The host name of the DNS server to change, or use `'localhost'` for the current node.
 - **`AdditionalTimeout` <Write, UInt32>** - Specifies the time interval, in seconds, that a DNS server waits as it uses recursion to get resource records from a remote DNS server. We recommend that you limit the value to the range 0x00000000 to 0x0000000F (0 seconds to 15 seconds), inclusive. However, you can use any value. We recommend that you set the default value to 4.
 - **`Enable` <Write, Boolean>** - Specifies whether the server enables recursion.
 - **`RetryInterval` <Write, UInt32>** - Specifies elapsed seconds before a DNS server retries a recursive lookup. If the parameter is undefined or zero, the DNS server retries after three seconds. Valid values are in the range of 1 second to 15 seconds. We recommend that in general, you do not change the value of this parameter. However, under a few circumstances you should consider changing the parameter value. For example, if a DNS server contacts a remote DNS server over a slow link and retries the lookup before it gets a response, you can raise the retry interval to be slightly longer than the observed response time.
 -  ~~**`SecureResponse` <Write, Boolean>** - Indicates whether a DNS server screens DNS records against the zone of authority for the remote server, to prevent cache pollution. If you set this to $True, the DNS server caches only those records that are in the zone of authority for the queried remote server. Otherwise, the server caches all records in the remote server cache.~~
 - **`Timeout` <Write, UInt32>** - Specifies the number of seconds that a DNS server waits before it stops trying to contact a remote server. The valid value is in the range of 0x1 to 0xFFFFFFFF (1 second to 15 seconds). The default setting is 0xF (15 seconds). We recommend that you increase this value when recursion occurs over a slow link.

### Special considerations or limitations
The default zone `'.'` that is set with `Set-DnsServerRecursionScope` is the same scope that is set with this resource. So in a future resource `DnsServerRecursionScope` it should prevent from changing the property `EnableRecursion` for the default scope (`'.'`) and instead refer to use this resource.

The parameters `Enable`, `RetryInterval`, `Timeout`, and `SecureResponse` replaces the properties `NoRecursion`, `RecursionRetry`, `RecursionTimeout`, and `SecureResponse` respectively in the resource **xDnsServerSetting**, To avoid ping-pong behavior those properties should be removed from the resource **xDnsServerSetting** once this issue is resolved.

### PR DESCRIPTION
**Pull request by johlju**
### Pull Request (PR) description
- DnsServerDsc
  - Added new resource
    - _DnsServerRecursion_ - resource to enforce recursion settings (issue #198).
- ResourceBase
  - Moved more logic from the resources into the base class for the method
    `Test()`, `Get()`, and `Set()`. The base class now have three methods
    `AssertProperties()`, `Modify()`, and `GetCurrentState()` where the
    two latter ones must be overridden by a resource if calling the base
    methods `Set()` and `Get()`.

### This Pull Request (PR) fixes the following issues

- Fixes #198

### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/245)

### CODE REVIEW

**Comment by johlju** [comment]
@Sudman1 I started moving more stuff into the base class `ResourceBase` from the resources (_still not touching `DnsRecordBase` though_). This approach simplifies the actual resources class even more, see resource _DnsRecourceRecursion_. I will add tests and stuff for the  _DnsRecourceRecursion_ later (I put this one in draft in the meantime). Ones this is merged I gonna fix the DnsServerCache, DnsServerEDns, and DnsServerScavenging to use the same approach. That will also able us to remove one of the overloads of `Get()` in `ResourceBase`.

**Comment by johlju** [comment]
Will add unit test for the class `ResourceBase`.

**Review by Sudman1 — COMMENTED** [review]
Looks good! I just have one discussion point on the methodology for the Get() method. But it can be tabled to push this commit if you like.

> Reviewed 6 of 10 files at r1, 4 of 5 files at r2, 4 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/245#-:-MXMGMIl6udhOzIkot0u:bg2u7d1)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[source/Classes/001.ResourceBase.ps1, line 54 at r4](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/245#-MXME9be6-mYQj-kg6pH:-MXME9bf-uheE_FyKHA4:b-9ij365) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/c7b60df06ece9464b1e4766fc888ac45091e07b0/source/Classes/001.ResourceBase.ps1#L54)):*
> ```PowerShell
>         }
> 
>         $getCurrentStateResult = $this.GetCurrentState($getParameters)
> ```

I like this methodology - and it's similar to what I've done in DnsRecordBase. But for this to be a parent of DnsRecordBase, the Get() method will need to be overridden to parse the DNS record CimInstances which are not flat like some of the more simple objects.

I'm good to sign off on this, but I feel like it might be more advantageous for GetCurrentState($getParameters) to do the work of constructing the return object itself.

**Review by Sudman1 — APPROVED** [review]
LGTM - see Reviewable for details.

**Review by johlju — COMMENTED** [review]
> Dismissed @Sudman1 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/245)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

___
*[source/Classes/001.ResourceBase.ps1, line 54 at r4](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/245#-MXME9be6-mYQj-kg6pH:-MXW9KGRABLAIPIHs5Yp:b-bxtafi) ([raw file](https://github.com/dsccommunity/dnsserverdsc/blob/c7b60df06ece9464b1e4766fc888ac45091e07b0/source/Classes/001.ResourceBase.ps1#L54)):*
<details><summary><i>Previously, Sudman1 (James Sudbury) wrote…</i></summary><blockquote>

I like this methodology - and it's similar to what I've done in DnsRecordBase. But for this to be a parent of DnsRecordBase, the Get() method will need to be overridden to parse the DNS record CimInstances which are not flat like some of the more simple objects.

I'm good to sign off on this, but I feel like it might be more advantageous for GetCurrentState($getParameters) to do the work of constructing the return object itself.
</blockquote></details>

I thought that it might be better for `GetCurrentState`to "normalize" the returned object, for example returning a `[Hashtable]`. We can look at that.

**Comment by johlju** [comment]
I merge this, so I can fix the other classes I created to the same pattern so we can get rid of the one overload that is unneccessary.

**Comment by johlju** [comment]
@Sudman1 thanks for the review and feedback! 😃

**Pull request merged**
