### PR TITLE
DnsServerDsSetting: New Resource to Manage AD DNS settings

### LINKED ISSUE #251: DnsServerDsSetting: New resource proposal
### Description
Suggest adding a new resource that changes DNS server Active Directory settings. Using the commands [`Get-DnsServerDsSetting`](https://docs.microsoft.com/en-us/powershell/module/dnsserver/get-dnsserverdssetting) and [`Set-DnsServerDsSetting`](https://docs.microsoft.com/en-us/powershell/module/dnsserver/set-dnsserverdssetting).

### Proposed properties
 - **`DnsServer` <Key, String>** - The host name of the DNS server to change, or use `'localhost'` for the current node.
 - **`DirectoryPartitionAutoEnlistInterval` <Write, String>** - Specifies the interval, during which a DNS server tries to enlist itself in a DNS domain partition and DNS forest partition, if it is not already enlisted. We recommend that you limit this value to the range one hour to 180 days, inclusive, but you can use any value. We recommend that you set the default value to one day. You must set the value 0 (zero) as a flag value for the default value. However, you can allow zero and treat it literally.
 - **`LazyUpdateInterval` <Write, UInt32>** - Specifies a value, in seconds, to determine how frequently the DNS server submits updates to the directory server without specifying the LDAP_SERVER_LAZY_COMMIT_OID control ([MS-ADTS] section 3.1.1.3.4.1.7) at the same time that it processes DNS dynamic update requests. We recommend that you limit this value to the range 0x00000000 to 0x0000003c. You must set the default value to 0x00000003. You must set the value zero to indicate that the DNS server does not specify the LDAP_SERVER_LAZY_COMMIT_OID control at the same time that it processes DNS dynamic update requests. For more information about LDAP_SERVER_LAZY_COMMIT_OID, see LDAP_SERVER_LAZY_COMMIT_OID control code. The LDAP_SERVER_LAZY_COMMIT_OID control instructs the DNS server to return the results of a directory service modification command after it is completed in memory but before it is committed to disk. In this way, the server can return results quickly and save data to disk without sacrificing performance. The DNS server must send this control only to the directory server that is attached to an LDAP update that the DNS server initiates in response to a DNS dynamic update request. If the value is nonzero, LDAP updates that occur during the processing of DNS dynamic update requests must not specify the LDAP_SERVER_LAZY_COMMIT_OID control if a period of less than DsLazyUpdateInterval seconds has passed since the last LDAP update that specifies this control. If a period that is greater than DsLazyUpdateInterval seconds passes, during which time the DNS server does not perform an LDAP update that specifies this control, the DNS server must specify this control on the next update.
 - **`MinimumBackgroundLoadThreads` <Write, UInt32>** - Specifies the minimum number of background threads that the DNS server uses to load zone data from the directory service. You must limit this value to the range 0x00000000 to 0x00000005, inclusive. You must set the default value to 0x00000001, and you must treat the value zero as a flag value for the default value.
 - **`PollingInterval` <Write, String>** - Specifies how frequently the DNS server polls Active Directory Domain Services (AD DS) for changes in Active Directory-integrated zones. You must limit the value to the range 30 seconds to 3,600 seconds, inclusive.
 - **`RemoteReplicationDelay` <Write, UInt32>** - Specifies the minimum interval, in seconds, that the DNS server waits between the time that it determines that a single object has changed on a remote directory server, to the time that it tries to replicate a single object change. You must limit the value to the range 0x00000005 to 0x00000E10, inclusive. You must set the default value to 0x0000001E, and you must treat the value zero as a flag value for the default value.
 - **`TombstoneInterval` <Write, String>** - Specifies the amount of time that DNS keeps tombstoned records alive in Active Directory. We recommend that you limit this value to the range three days to eight weeks, inclusive, but you can set it to any value in the range 82 hours to 8 weeks. We recommend that you set the default value to 14 days and treat the value zero as a flag value for the default. However, you can allow the value zero and treat it literally. At 2:00 A.M. local time every day, the DNS server must search all directory service zones for nodes that have the Active Directory dnsTombstoned attribute set to True, and for a directory service EntombedTime (section 2.2.2.2.3.23 of MS-DNSP) value that is greater than previous directory service DSTombstoneInterval seconds. You must permanently delete all such nodes from the directory server.

### Special considerations or limitations
The parameters `DirectoryPartitionAutoEnlistInterval` and `TombstoneInterval` are of the type `[String]` that should be converted to `[TimeSpan]` similar to the `TTL` parameter here:
https://github.com/dsccommunity/xDnsServer/blob/dbcdb067ce905e7c3fc5f74d1ad787c3166f33ba/source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1#L200-L203

The parameters `TombstoneInterval` and `PollingInterval` replaces the properties `DsPollingInterval` and `DsTombstoneInterval`  in the resource **xDnsServerSetting**, To avoid ping-pong behavior those properties should be removed from the resource **xDnsServerSetting** once this issue is resolved.

### PR DESCRIPTION
**Pull request by Sudman1**
### Pull Request (PR) description

Implements Get-DnsServerDsSetting and Set-DnsServerDsSetting as a DSC resource.

### This Pull Request (PR) fixes the following issues

- Fixes #251

### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [N/A] Resource documentation added/updated in README.md.
- [N/A] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/258)

### CODE REVIEW

**Comment by Sudman1** [comment]
@johlju - your ResourceBase class made this resource's creation super easy. I was amazed. Now we need to make it just as easy to generate the examples and tests!

**Comment by johlju** [comment]
Glad to hear! It took a few iterations to get there, and still work to do. But I really made each resource simple 😄

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/258#-:-Ma2huLZ49rpP3kMAGuV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Sudman1)

**Comment by johlju** [comment]
@Sudman1 awesome work! No comments at all. 😄

**Pull request merged**
