### PR TITLE
Migrate to Pester 5

### PR DESCRIPTION
**Pull request by dan-hughes**
### Pull Request (PR) description

Update the tests to use Pester 5. Module changes will be kept to a minimum.

### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272)

### CODE REVIEW

**Comment by dan-hughes** [comment]
@johlju can you azp run please?

**Comment by johlju** [comment]
Can you update the line installing GitVersion in azure-pipelines.yml to https://github.com/gaelcolas/Sampler/issues/477#issuecomment-2245841500? That will be needed or the build will fail even if I kick it again.

**Comment by dan-hughes** [comment]
Done. I set the --version to 5.* to allow any future updates available to v5.

**Comment by dan-hughes** [comment]
@johlju, what's a gold standard for class implementation and tests I can reference? I'm onto the classes and this uses it's own base class from the bottom up. 
I've started inheriting from DscResource.Base, but it's significant change, but it brings many benefits and remove many duplicate functions and tests which are provided by the Base and Common modules.

**Comment by johlju** [comment]
Any work to migrate class-based resources should best be done in separate PR(s). 🙂 This PR is gonna be quite big without adding that too 😉

**Comment by johlju** [comment]
SqlServerDsc have tests for classes and you can look at: https://github.com/dsccommunity/SqlServerDsc/blob/main/tests/Unit/Classes/SqlAudit.Tests.ps1

**Comment by dan-hughes** [comment]
> A bit of a history... This repo started the journey to the module DscResource.Base with the work @Sudman1 started with implementing `DsnRecordBase`, that inspired `ResourceBase` that in turn inspired the module DscResource.Base. 🙂
> 
> DnsResource.Base is an opiniated way of created class-based resource and can't say that it is the gold standard, but that is what I use when writting class-based resource because as you said, to reduce duplication. The repo SqlServerDsc is where I personally made most work with class-based resource using that opiniated way. In that repo there is also a class `SqlResourceBase` that all class-based resource inherits from, and `SqlResourceBase` inherits `ResourceBase` (DscResource.Base).
> 
> II have no issue with class-based resource being modified to use the module DscResource.Base, but the existing can also be kept the way they are and ny class-based resource using another pattern like DscResource.Base. 🤔 Though, class-based resource using the the class `ResourceBase` that is part of this repo should probably be migrated to DscResource.Base. 🤔

Thanks. I'm not moving any script resources to use classes, any that currently used classes I'm trying to alter to use `DscResource.Base`.  You are right though, this is going to be a large PR to move to Pester 5. 
I'm thinking of abandoning the move to `DscResource.Base` and bring that along separately as to align it requires some major surgery too!

**Comment by dan-hughes** [comment]
@johlju, I got it all working!

I don't quite understand why the classes which inherit from `DscResource.Base` are being shown with code coverage missing. I added some explicit tests for the function it's complaining about and it did not make a difference.

**Comment by johlju** [comment]
Will get to this soon. It large so need a few hour for it 🙂

**Review by johlju — CHANGES_REQUESTED** [review]
Looks good, just a few tiny comments. I did not go into detail in changed tests, I will assume they are working as expected. :slightly_smiling_face:  Awesome work on this one!

> Reviewed 23 of 56 files at r1, 1 of 1 files at r2, 5 of 15 files at r3, 20 of 46 files at r4, 31 of 40 files at r5, 10 of 11 files at r6, 30 of 30 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-:-O4_8BOt8dAI8A8CInRP:b1dn4h1)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-hughes)

___
*[`source/DnsServerDsc.psm1` line 0 at r7](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4ZzJNt7EsB6X2TtMmS:-O4ZzJNuCNEZMCd_J2nc:bpm1bp1) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/016b74f78fe98c8b7fe14ca0cf19cca8391a4b94/source/DnsServerDsc.psm1#L0)):*
Should we remove this? I think this file is there so the .psd1 file has something to reference when it is parsed. It was something that failed when this file was removed,  but that was a long time ago and the reason might no longer exist. Thinking if there is a scenarion when this file is used (imported/parsed) in a way that could fail, but can't think of one. So let us remove it and see if something fails down the line. :slightly_smiling_face: 
___
*[`source/Enum/1.Ensure.ps1` line 1 at r4](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4_7m7B7rIn1SZdZE2u:-O4_7m7B7rIn1SZdZE2v:b-ged6sy) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/2552eeb30480bdf8827c90e0f8534c3926d87ef3/source/Enum/1.Ensure.ps1#L1)):*
> ```PowerShell
> enum Ensure
> ```

See you removed this then reverted it so it is kept, do we still need this here even though it is part of DscResource.Base?
___
*[`source/Classes/030.DnsServerCache.ps1` line 129 at r7](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4_2472D4rO69QTYLjs:-O4_2472D4rO69QTYLjt:b-xlrt84) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/016b74f78fe98c8b7fe14ca0cf19cca8391a4b94/source/Classes/030.DnsServerCache.ps1#L129)):*
> ```PowerShell
>         {
>             $getParameters.ComputerName = $properties.DnsServer
>         }
> ```

Why do we need all this code? Since DnsServer is a key property it will always be part of $properties. So can't we always set that directly? User can se the DsnServer property to localhost if they want. :thinking: 

Same comment throughout the resources.



_Suggestion:_
```PowerShell
        $getParameters.ComputerName = $properties.DnsServer
```

**Review by dan-hughes — COMMENTED** [review]
The DnsServerRecord tests are largely the same format, I added some tests that were missing. 

I would it be better if I highlighted some that I have concerns about so I can apply any patterns/learning across the board?

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-:-O4_ExgN-kU7mA35I9zx:b-gr1hcn)* status: all files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[`source/DnsServerDsc.psm1` line  at r7](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4ZzJNt7EsB6X2TtMmS:-O4_Cs1Q3b_114A0atNT:bxvvyz6) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/016b74f78fe98c8b7fe14ca0cf19cca8391a4b94/source/DnsServerDsc.psm1#L)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should we remove this? I think this file is there so the .psd1 file has something to reference when it is parsed. It was something that failed when this file was removed,  but that was a long time ago and the reason might no longer exist. Thinking if there is a scenarion when this file is used (imported/parsed) in a way that could fail, but can't think of one. So let us remove it and see if something fails down the line. :slightly_smiling_face:
</blockquote></details>

I had to remove this for the tests to work, I think when this existed  HQRM tests failed.

I checked SqlServerDsc and this file is missing too.
___
*[`source/Enum/1.Ensure.ps1` line 1 at r4](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4_7m7B7rIn1SZdZE2u:-O4_DzxTA-FTXh-05q_k:b-29jp34) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/2552eeb30480bdf8827c90e0f8534c3926d87ef3/source/Enum/1.Ensure.ps1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

See you removed this then reverted it so it is kept, do we still need this here even though it is part of DscResource.Base?
</blockquote></details>

Long story, I looked at converting all resources to inherit from DscResource.Base but the DnsServerRecord* resources is way more work so I will do that on another PR.

I can try removing, but this PR is so large that I didn't want to potentially break something else. 

Want me to try or leave it to the next PR (which I have here partly complete)?
___
*[`source/Classes/030.DnsServerCache.ps1` line 129 at r7](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4_2472D4rO69QTYLjs:-O4_Da1O6ygNmQnYdRg0:b-g7i1wz) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/016b74f78fe98c8b7fe14ca0cf19cca8391a4b94/source/Classes/030.DnsServerCache.ps1#L129)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Why do we need all this code? Since DnsServer is a key property it will always be part of $properties. So can't we always set that directly? User can se the DsnServer property to localhost if they want. :thinking: 

Same comment throughout the resources.
</blockquote></details>

I thought that it was because the property did not have a default value, but you make a good point that as it's a key property then it always will be defined. I shall fix.

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-hughes)

___
*[`source/DnsServerDsc.psm1` line  at r7](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4ZzJNt7EsB6X2TtMmS:-O4_QOXDACpBIkG6TN-B:beo1xy1) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/016b74f78fe98c8b7fe14ca0cf19cca8391a4b94/source/DnsServerDsc.psm1#L)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

I had to remove this for the tests to work, I think when this existed  HQRM tests failed.

I checked SqlServerDsc and this file is missing too.
</blockquote></details>

Hmm. So it is. Forgot we did that. Cool. All good then. :slightly_smiling_face: 
___
*[`source/Enum/1.Ensure.ps1` line 1 at r4](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4_7m7B7rIn1SZdZE2u:-O4_QdKt208SQIlMBtMe:b-mf0caq) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/2552eeb30480bdf8827c90e0f8534c3926d87ef3/source/Enum/1.Ensure.ps1#L1)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Long story, I looked at converting all resources to inherit from DscResource.Base but the DnsServerRecord* resources is way more work so I will do that on another PR.

I can try removing, but this PR is so large that I didn't want to potentially break something else. 

Want me to try or leave it to the next PR (which I have here partly complete)?
</blockquote></details>

Leave it for the next PR.  :slightly_smiling_face: 
___
*[`source/Classes/030.DnsServerCache.ps1` line 101 at r7](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4_PD27ADU0efQojsvp:-O4_PD27ADU0efQojsvq:b-pclk51) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/016b74f78fe98c8b7fe14ca0cf19cca8391a4b94/source/Classes/030.DnsServerCache.ps1#L101)):*
> ```PowerShell
> 
>     [DscProperty(NotConfigurable)]
>     [Reason[]]
> ```

We need to make this class unique otherwise it can fail if two modules define the same class twice. See SqlServerDsc here: 
https://github.com/dsccommunity/SqlServerDsc/blob/3c3092976409645d74f58707331f66ffe1967127/source/Classes/011.SqlResourceBase.ps1#L45-L47

And the uniquely class here: https://github.com/dsccommunity/SqlServerDsc/blob/main/source/Classes/001.SqlReason.ps1

And issue explained here: https://github.com/dsccommunity/DscResource.Base/issues/4

This can be fixed in the next PR too.

**Review by dan-hughes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272)* status: all files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[`source/Classes/030.DnsServerCache.ps1` line 101 at r7](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4_PD27ADU0efQojsvp:-O4_aP773VuCOPa7hlXW:b-vmmy1d) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/016b74f78fe98c8b7fe14ca0cf19cca8391a4b94/source/Classes/030.DnsServerCache.ps1#L101)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We need to make this class unique otherwise it can fail if two modules define the same class twice. See SqlServerDsc here: 
https://github.com/dsccommunity/SqlServerDsc/blob/3c3092976409645d74f58707331f66ffe1967127/source/Classes/011.SqlResourceBase.ps1#L45-L47

And the uniquely class here: https://github.com/dsccommunity/SqlServerDsc/blob/main/source/Classes/001.SqlReason.ps1

And issue explained here: https://github.com/dsccommunity/DscResource.Base/issues/4

This can be fixed in the next PR too.
</blockquote></details>

Okay, what's the point of `[Reasons]` in `DscResource.Base` if each module needs to implement their own? Or is it for the functionality in `DscResource.Base` to populate the reason it has to exist?

Will it work if this module has a `[DnsServerReasons]` which inherits from `[Reasons]`? Or does it need to be it's own isolated implementation?

**Review by johlju — COMMENTED** [review]
Sure you can do that.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-:-O4_fKrh6lkdn9TOmFgR:b2bvco9)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-hughes)

___
*[`source/Classes/030.DnsServerCache.ps1` line 101 at r7](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4_PD27ADU0efQojsvp:-O4_fRa50RUUGVojlkGb:bgl06sp) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/016b74f78fe98c8b7fe14ca0cf19cca8391a4b94/source/Classes/030.DnsServerCache.ps1#L101)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Okay, what's the point of `[Reasons]` in `DscResource.Base` if each module needs to implement their own? Or is it for the functionality in `DscResource.Base` to populate the reason it has to exist?

Will it work if this module has a `[DnsServerReasons]` which inherits from `[Reasons]`? Or does it need to be it's own isolated implementation?
</blockquote></details>

It cannot inherit, it must be its own implementation. 

The reason for it being left in DscResource.Base is that the derived class can use an hashtable array instead. DscResource.base will convert to its own `Reasons` class. But this method has not been used by a resource yet what I know of. See "Suggested solution" in the  issue above.

```
[DscProperty(NotConfigurable)]
[System.Collections.Hashtable[]]
$Reasons
```

**Review by dan-hughes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272)* status: 82 of 123 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[`source/Classes/030.DnsServerCache.ps1` line 129 at r7](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4_2472D4rO69QTYLjs:-O4a4kQeDkDNYvebSpnU:b-wodxsh) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/016b74f78fe98c8b7fe14ca0cf19cca8391a4b94/source/Classes/030.DnsServerCache.ps1#L129)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

I thought that it was because the property did not have a default value, but you make a good point that as it's a key property then it always will be defined. I shall fix.
</blockquote></details>

Done, but final one on this, keep the splat or save the variable for only one property?

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 41 of 41 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-hughes)

___
*[`tests/Unit/DSC_DnsServerDiagnostics.Tests.ps1` line 539 at r8](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4aBA-i4OJNJOsvqRnO:-O4aBA-i4OJNJOsvqRnP:b6xzhea) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/6deccfbeb2a99eeb44fc9409672d66a78ab1ac54/tests/Unit/DSC_DnsServerDiagnostics.Tests.ps1#L539)):*
> ```PowerShell
>             Set-TargetResource @testParameters
>         }
>         
> ```

Looks like we got some spaces here that Reviewable is indicating.
___
*[`tests/Unit/Classes/DnsRecordCname.tests.ps1` line 467 at r8](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4aBbbTAAVW0MvZ9z6z:-O4aBbbTAAVW0MvZ9z7-:bbqszip) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/6deccfbeb2a99eeb44fc9409672d66a78ab1ac54/tests/Unit/Classes/DnsRecordCname.tests.ps1#L467)):*
> ```PowerShell
>                 InModuleScope -ScriptBlock {
>                     Set-StrictMode -Version 1.0
>                     
> ```

Empty spaces here too. 
___
*[`tests/Unit/Classes/DnsServerScavenging.Tests.ps1` line 537 at r8](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4aCwf427o_VmJ92L-d:-O4aCwf427o_VmJ92L-e:b2o4jsf) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/6deccfbeb2a99eeb44fc9409672d66a78ab1ac54/tests/Unit/Classes/DnsServerScavenging.Tests.ps1#L537)):*
> ```PowerShell
>                 $currentState.LastScavengeTime | Should -Be '2021-01-01 00:00:00'
>             }
>             
> ```

Empty spaces here too.
___
*[`source/Classes/030.DnsServerCache.ps1` line 129 at r7](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4_2472D4rO69QTYLjs:-O4aAQMjBvb1z1M2gP0k:btl5o4) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/016b74f78fe98c8b7fe14ca0cf19cca8391a4b94/source/Classes/030.DnsServerCache.ps1#L129)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Done, but final one on this, keep the splat or save the variable for only one property?
</blockquote></details>

I good either way. Using splatting makes the line a bit shorter than if we wouldn't.

**Review by dan-hughes — COMMENTED** [review]
I checked most things and I think it's good for the time being. Up to you if you want to do any random spot checks? 

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-:-O4aKnzD3NBGJ2y4SqTL:b-i1o7fn)* status: all files reviewed, 3 unresolved discussions (waiting on @johlju)

___
*[`tests/Unit/DSC_DnsServerDiagnostics.Tests.ps1` line 539 at r8](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4aBA-i4OJNJOsvqRnO:-O4aKzlF7-PbMW09jTyu:b-4cfit) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/6deccfbeb2a99eeb44fc9409672d66a78ab1ac54/tests/Unit/DSC_DnsServerDiagnostics.Tests.ps1#L539)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Looks like we got some spaces here that Reviewable is indicating.
</blockquote></details>

Weird, this one. Did not show up as spaces. I deleted all the line breaks and it now shows as a change in Git.
___
*[`tests/Unit/Classes/DnsRecordCname.tests.ps1` line 467 at r8](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4aBbbTAAVW0MvZ9z6z:-O4aLCqxDsuXUYI-IK2n:b-896fix) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/6deccfbeb2a99eeb44fc9409672d66a78ab1ac54/tests/Unit/Classes/DnsRecordCname.tests.ps1#L467)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Empty spaces here too.
</blockquote></details>

Done.
___
*[`tests/Unit/Classes/DnsServerScavenging.Tests.ps1` line 537 at r8](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4aCwf427o_VmJ92L-d:-O4aLDD63tEJeW2SQTMR:b-896fix) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/6deccfbeb2a99eeb44fc9409672d66a78ab1ac54/tests/Unit/Classes/DnsServerScavenging.Tests.ps1#L537)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Empty spaces here too.
</blockquote></details>

Done.

**Review by johlju — COMMENTED** [review]
Did a read through on a integration test and unit test, they looked good. Just had some suggestions. But up to you if you want to improve them. I could LGTM this one now too.

> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-:-O4aa4bqDX9oVK95UTJz:bsrkui3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)

___
*[`tests/Integration/Classes/DnsRecordCname.integration.tests.ps1` line 67 at r9](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4aYgRe-txJwr0q63ql:-O4aYgRe-txJwr0q63qm:brwpuok) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/aece735d7a8652b7ba742ddab448c973ac6b3611/tests/Integration/Classes/DnsRecordCname.integration.tests.ps1#L67)):*
> ```PowerShell
>         BeforeAll {
>             $configurationName = "$($script:dscResourceName)_CreateRecord_Config"
>         }
> ```

Instead of duplicating the configurationName in both discovery phase and run. phase it is possible to get it from. the discovery phase by doing this:

https://github.com/dsccommunity/SqlServerDsc/blob/3c3092976409645d74f58707331f66ffe1967127/tests/Integration/Resources/DSC_SqlAudit.Integration.Tests.ps1#L58-L63



_Code quote:_
```PowerShell
    BeforeDiscovery {
        $configurationName = "$($script:dscResourceName)_CreateRecord_Config"
    }

    Context ('When using configuration {0}' -f $configurationName) {
        BeforeAll {
            $configurationName = "$($script:dscResourceName)_CreateRecord_Config"
        }
```
___
*[`tests/Unit/Classes/DnsServerCache.Tests.ps1` line 94 at r9](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4a_QGjDua0V2cZ1Whl:-O4a_QGjDua0V2cZ1Whm:bprcfwr) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/aece735d7a8652b7ba742ddab448c973ac6b3611/tests/Unit/Classes/DnsServerCache.Tests.ps1#L94)):*
> ```PowerShell
>                 Set-StrictMode -Version 1.0
> 
>                 $script:instance = [DnsServerCache] @{
> ```

A suggestion is always prefix variables with `mock`, e,g. `$script:mockInstance`. This prevents setting a variable name that is actually used in classes by mistake, since we are setting the variable in the module scope and the modules script scope. 



_Code quote:_
```PowerShell
$script:instance
```

**Comment by dan-hughes** [comment]
@johlju, I don't mind doing it via this PR. Already got it open and they're minor. It also helps get a good reference for me or anyone else in the future. Keep an eye out over the next few days.

**Review by dan-hughes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272)* status: 89 of 123 files reviewed, all discussions resolved (waiting on @johlju)

___
*[`tests/Integration/Classes/DnsRecordCname.integration.tests.ps1` line 67 at r9](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4aYgRe-txJwr0q63ql:-O4ao8X2-b9wnapEJ3sx:b-5y3p72) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/aece735d7a8652b7ba742ddab448c973ac6b3611/tests/Integration/Classes/DnsRecordCname.integration.tests.ps1#L67)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Instead of duplicating the configurationName in both discovery phase and run. phase it is possible to get it from. the discovery phase by doing this:

https://github.com/dsccommunity/SqlServerDsc/blob/3c3092976409645d74f58707331f66ffe1967127/tests/Integration/Resources/DSC_SqlAudit.Integration.Tests.ps1#L58-L63
</blockquote></details>

This was a much larger change than I originally thought :-).

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 34 of 34 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-:-O4eY9r16JQUphvP9R6Q:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)

___
*[`tests/Integration/Classes/DnsRecordCname.integration.tests.ps1` line 67 at r9](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4aYgRe-txJwr0q63ql:-O4eV4ovBUhx540I2NPG:b1j3fwn) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/aece735d7a8652b7ba742ddab448c973ac6b3611/tests/Integration/Classes/DnsRecordCname.integration.tests.ps1#L67)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

This was a much larger change than I originally thought :-).
</blockquote></details>

Yes, that is why I gave the option to not do it :wink: Awesome work! 

Not for this PR, but.. A thought I had several times... Ultimately I think it would be great if we could pass in a hashtable array with all the configuration names and a key `ExpectedResult` that has a hashtable or PSCustomObject with the expected result. Then one Context-block could loop through all configurations and not need to duplicate all the It-blocks... But maybe it would also make the tests less readable when debugging so haven't put in the time. :slightly_smiling_face: 

This looks good now!

**Comment by johlju** [comment]
Awesome work on this! Thank you!

**Comment by dan-hughes** [comment]
> :lgtm:
> 
> > Reviewed 34 of 34 files at r10, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-:-O4eY9r16JQUphvP9R6Q:bnfp4nl)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)
> 
> _[`tests/Integration/Classes/DnsRecordCname.integration.tests.ps1` line 67 at r9](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/272#-O4aYgRe-txJwr0q63ql:-O4eV4ovBUhx540I2NPG:b1j3fwn) ([raw file](https://github.com/dsccommunity/DnsServerDsc/blob/aece735d7a8652b7ba742ddab448c973ac6b3611/tests/Integration/Classes/DnsRecordCname.integration.tests.ps1#L67)):_
> 
> Previously, dan-hughes (Daniel Hughes) wrote…
> Yes, that is why I gave the option to not do it 😉 Awesome work!
> 
> Not for this PR, but.. A thought I had several times... Ultimately I think it would be great if we could pass in a hashtable array with all the configuration names and a key `ExpectedResult` that has a hashtable or PSCustomObject with the expected result. Then one Context-block could loop through all configurations and not need to duplicate all the It-blocks... But maybe it would also make the tests less readable when debugging so haven't put in the time. 🙂
> 
> This looks good now!

I think it's a pick your poison situation. Yes the tests are verbose but they're flexible and easy enough for someone like me to read and pick up in most cases. 
It's possibly an option here with class resources that all inherit from the same base class, as making broad changes like a Pester major version upgrade would be faster but it feels a little cleaner knowing only working on a resource could only break the tests for that resource.

**Pull request merged**
