### PR TITLE
DnsServerDsc: Fixed code coverage in the pipeline

### LINKED ISSUE #246: DnsServerDsc: Codecov.io does not show coverage for classes
Because the the classes are built into the DnsServerDsc.psm1 there is no comparable file for Codecov.io to report on. With the current implementation it finds source/DnsServerDsc.psm1 which is empty so it cannot record the hits/misses on that file.

The same problem ecist for Azure DevOps coverage.

We need to work out the line in `./output/.../DnsServerDsc.psm1` to the correct line in the actual class file and modify the coverage file before uploading it. ModuleBuilder has functionality for this, see:

https://github.com/dsccommunity/DscResource.DocGenerator/pull/12#issuecomment-583864591

### PR DESCRIPTION
**Pull request by johlju**
### Pull Request (PR) description
- DnsServerDsc
  - Fixed code coverage in the pipeline (issue #246).

### This Pull Request (PR) fixes the following issues

- Fixes #246

### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/253)

### CODE REVIEW

**Comment by johlju** [comment]
@Sudman1 now code coverage works for classes:

Codecov.io: https://app.codecov.io/gh/dsccommunity/DnsServerDsc/compare/253/tree/source
AzDO: https://dev.azure.com/dsccommunity/DnsServerDsc/_build/results?buildId=4325&view=codecoverage-tab

**Comment by Sudman1** [comment]
That is a great change. Do we happen to know why there are some pipeline failures? Their existence doesn't make sense to me based on the changes made.

**Comment by johlju** [comment]
Yes, a bug in the new task that fixes coverage for class resources. Pushed a release, so should be fixed soon. I re-run this PR tomorrow.

**Review by johlju — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/253#-:-MXp9lpn-Wvewu-poThr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Pull request merged**
